services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Web UI http://localhost:8025
